### ISSUE TITLE
Show on page load, timed hide

### ISSUE THREAD

**Issue by deanturpin** [deanturpin/greasemonkey#12]
Wait 10s before hiding?

**Comment by deanturpin** [comment]
```css
@keyframes cssAnimation {
    0%   {opacity: 1;}
    90%  {opacity: 1;}
    100% {opacity: 0;}
}
```

https://stackoverflow.com/questions/21993661/css-auto-hide-elements-after-5-seconds
